---
- name: Retrieve information about currently installed kubernetes version
  hosts: all
  become: yes
  roles:
    - role: kube-version

- name: Drain and delete all nodes
  hosts: master
  become: yes
  tasks:
    - name: Drain all nodes
      command: kubectl --kubeconfig {{ kubeconfig }} drain {{ hostvars[item]["ansible_nodename"] }} --delete-local-data --force --ignore-daemonsets
      ignore_errors: yes
      failed_when: false
      loop: '{{ groups["all"] }}'
      
    - name: Delete all nodes
      command: kubectl --kubeconfig {{ kubeconfig }} delete node {{ hostvars[item]["ansible_nodename"] }}
      ignore_errors: yes
      failed_when: false
      loop: '{{ groups["all"] }}'

- name: Revert kubernetes installation
  hosts: all
  become: yes
  roles:
    - role: cluster-destroy
