---
# UPDATES kubernetes cluster based on kubeadm configuration file
# i.e. this playbook can be used to update the various static manifests of different kubernetes components

- name: Retrieve information about currently installed kubernetes version
  hosts: all
  become: yes
  roles:
    - role: kube-version

- name: Perform cluster update for first control plane node
  hosts: master
  become: yes
  roles:
    - role: cluster-update
      control_plane_node: true
      first_control_plane_node: true
      when: kubernetes_installed is true

- name: Update additional control plane nodes
  hosts: extra_masters
  become: yes
  serial: 1
  roles:
    - role: cluster-update
      control_plane_node: true
      first_control_plane_node: false
      when: kubernetes_installed is true

- name: Update worker nodes
  hosts: workers
  become: yes
  serial: 1
  roles:
  - role: cluster-update
    control_plane_node: false
    first_control_plane_node: false
    when: kubernetes_installed is true

- name: Get kubernetes nodes
  hosts: master
  become: yes
  roles:
    - role: node-get
