---
- name: Retrieve information about currently installed kubernetes version
  hosts: all
  become: yes
  roles:
    - role: kube-version

- name: Prepare nodes to install kubeadm
  hosts: all
  become: yes
  roles:
   - prerequisites  

- name: Initialise control plane on master node
  hosts: master
  become: yes
  roles:
    - role: cluster-create

- name: Join additional master nodes to cluster
  hosts: extra_masters
  become: yes
  roles:
    - role: node-join
      control_plane: true

- name: Join worker nodes to cluster
  hosts: workers
  become: yes
  roles:
    - role: node-join
      control_plane: false
