all:
  children:
    master:
      hosts:
        <IP_OF_CONTROL_PLANE_NODE_1>:
    extra_masters:
      hosts:
        <IP_OF_CONTROL_PLANE_NODE_2>:
        <IP_OF_CONTROL_PLANE_NODE_3>:
    workers:
      hosts:
        <IP_OF_WORKER_NODE_1>:
        <IP_OF_WORKER_NODE_2>:
        <IP_OF_WORKER_NODE_3>: