all:
  children:
    master:
      hosts:
        192.168.50.21:
    extra_masters:
      hosts:
        192.168.50.22:
    workers:
      hosts:
        192.168.50.23:
        192.168.50.24:
