---
# Kubeadm cluster configuration file
# Refer here for full reference https://kubernetes.io/docs/reference/config-api/kubeadm-config.v1beta3/
# DO NOT change kubernetesVersion field here

# controlPlaneEndpoint field must be set to a domain name for HA clusters
# If you prefer to create a single control plane node cluster and are not planning to expand, set this field to ""
# kubeadm DOES NOT support adding extra control plane nodes if controlPlaneEndpoint is set to ""
# https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/#considerations-about-apiserver-advertise-address-and-controlplaneendpoint

kind: ClusterConfiguration
apiVersion: kubeadm.k8s.io/v1beta3
kubernetesVersion: v{{ version.kubernetes }} 
controlPlaneEndpoint: kube-apiserver.lab.kevinf.xyz
etcd:
  local: 
    extraArgs: {}
apiServer:
  extraArgs: {}
controllerManager:
  extraArgs: {}
  extraVolumes:
  - name: tz-info
    hostPath: /usr/share/zoneinfo/Australia/Sydney
    mountPath: /etc/localtime
    readOnly: true
    pathType: File
scheduler:
  extraArgs: {}
networking:
  serviceSubnet: 10.96.0.0/12
  podSubnet: 10.32.0.0/12
---
kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
cgroupDriver: systemd
---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
metricsBindAddress: "0.0.0.0:10249"
