---
- name: Copy kubeadm init config file
  template: 
    src: ../../cluster-create/templates/kubeadm-config.yaml.j2
    dest: /etc/kubernetes/kubeadm-config.yaml
  when: first_control_plane_node is true

- name: Copy audit policy config file
  copy: 
    src: ../../cluster-create/files/audit-policy.yaml
    dest: /etc/kubernetes/audit-policy.yaml
  when: control_plane_node is true

- name: Verify difference
  command: kubeadm upgrade diff --config /etc/kubernetes/kubeadm-config.yaml
  register: upgrade_diff_output
  when: first_control_plane_node is true

- name: Print information about manifests to update
  debug:
    var: upgrade_diff_output["stdout_lines"]
  when: first_control_plane_node is true

- name: Update first control plane node
  command: kubeadm upgrade apply --config /etc/kubernetes/kubeadm-config.yaml -y
  when: first_control_plane_node is true

- name: Update other nodes
  command: kubeadm upgrade node
  when: first_control_plane_node is false
