---
# Cleans up kubernetes cluster installation on all nodes

- name: Revert kubeadm changes
  command: kubeadm reset -f

- name: Clean IPTables entries
  shell: iptables -F && iptables -t nat -F && iptables -t mangle -F && iptables -X
  