---
# Configures kernel settings for kubernetes components and containerd runtime

- name: Disable swap
  command: swapoff -a

- name: Disable swap in fstab
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'

- name: Load netfilter module (allows iptables to see bridged traffic)
  command: modprobe br_netfilter

- name: Load overlay module (required for containerd)
  command: modprobe overlay

- name: Load netfilter and overlay modules on startup 
  copy:
    src: modules-k8s.conf
    dest: /etc/modules-load.d/k8s.conf

- name: Load required sysctl settings to see bridged traffic and for IP forwarding
  copy: 
    src: sysctl-k8s.conf
    dest: /etc/sysctl.d/k8s.conf

- name: Apply sysctl
  command: sysctl --system


