---
# Installs and configures containerd
# Also updates other packages on OS and reboots if required

- name: Install containerd
  apt:
    update_cache: no
    name: 
      - containerd.io

- name: Make containerd folder
  command: mkdir -p /etc/containerd

- name: Move containerd configuration
  copy:
    src: containerd-config.toml
    dest: /etc/containerd/config.toml
  notify:
    - restart-containerd

- name: Install kubernetes componenets
  apt:
    update_cache: no
    name:
      - kubelet={{ kube_version_install }}*
      - kubeadm={{ kube_version_install }}*
      - kubectl={{ kube_version_install }}*

- name: Hold kubernetes components
  command: apt-mark hold kubelet kubeadm kubectl

- name: Upgrade rest of OS packages
  apt:
    update_cache: no
    upgrade: yes

- name: Check if reboot required
  stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: Reboot if required
  reboot:
  when: reboot_required_file.stat.exists == true
