---
# Checks whether kubernetes is already installed on node

- name: Set kubeconfig location fact for control plane nodes
  set_fact:
    kubeconfig: /etc/kubernetes/admin.conf
  when: "('master' in group_names) or ('extra_masters' in group_names)"

- name: Set kubeconfig location fact for worker nodes
  set_fact:
    kubeconfig: /etc/kubernetes/kubelet.conf
  when: "'workers' in group_names"

- name: Check if kubernetes is already installed
  command: kubectl --kubeconfig {{ kubeconfig }} cluster-info
  ignore_errors: true
  failed_when: false
  changed_when: false
  register: kubernetes_installed_check

- name: Set fact for use in future plays
  set_fact:
    kubernetes_installed: '{{ true if (kubernetes_installed_check["rc"] == 0) else false }}' 

- name: Get kubernetes version
  command: kubectl --kubeconfig {{ kubeconfig }} version --short=true 
  ignore_errors: true
  failed_when: false
  changed_when: false
  register: kubernetes_version_check

- name: Set fact for use in future plays
  set_fact:
    kubernetes_version: '{{ kubernetes_version_check["stdout_lines"][1].split(" ")[-1][1:] if kubernetes_installed else "" }}'
